### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by zimond** [dylanede/vulkan-malloc#1]
1. In `allocation.rs#free_suballocation()`, it should be `self.merge_free_with_next(item.clone())`, not`merge_free_with_next(next_item)`.

2. The List implementation's `insert_after` & `insert_before` methods forget to set relative references of `current_next.prev` & `current_prev.next`, which leads to many errors

This crate still contains some other bugs, cannot find them yet.

**Comment by zimond** [comment]
3rd: In `merge_free_with_next`, `self.free_count -= 1;` is needed after the item being removed from the suballocation list. Or `Allocation::validate()` won't pass.

The allocator also crashes when concurrently dropping. So it's in fact not sync + send ready.

**Comment by zimond** [comment]
The final bug should be the usage of `binary_search_by` in `unregister_free_suballocation`. The returned `index` is not guaranteed to be the first suballocation having target `size`. So the loop following may find no correct sub allocation and lead to a panic.

**Comment by dylanede** [comment]
Hi, thanks for the bug reports! I've just committed changes that should fix the reported issues, though I'd just like to clarify whether the concurrent dropping bug is due to the other bugs or not.

It sounds like you've got some decent test cases for each of these bugs - would it be possible for you to share them? Thanks.

**Comment by zimond** [comment]
Never mind about the concurrent problem. I found that it's because of the `binary_search_by` bug.

I'm trying to use this allocator in my vulkan project. So I have no tests XD

**Comment by daiheitan** [comment]
So I used the latest bug fix and create images in multiple threads, the thread validation layer reports attempting to map memory to already mapped objects, unmapping memory that is not mapped...etc. So I guess the sync code still has some problems

**Comment by dylanede** [comment]
Regarding your (presumably deleted) comment about memory mapping issues, you've probably figured out that it is due to this bit of the documentation, for the `own_memory` field in `AllocatorMemoryRequirements`:

> This flag must also be used for host visible resources that you want to map simultaneously because otherwise they might end up as regions of the same DeviceMemory, and mapping the same DeviceMemory multiple times is illegal.

For resources that you wish to map simultaneously but not resort to `own_memory` for, the recommended solution is to use multiple allocators, for example one per thread that is allocating and mapping resources.

Unless you find any more problems beforehand, I will close this issue once I've done a patch release.

**Comment by zimond** [comment]
The original AMD allocator could be used cross threads. My problem is that when mapping memory, an extra lock is need so that the same `DeviceMemory` is not mapped twice at the same time. I think it's not strictly a bug (the extra lock could be supported in this crate though). Anyway I deleted the comment

**Comment by dylanede** [comment]
With what version of the original AMD allocator was that? This crate was written with the pre-2.0 version of the AMD code as reference. That piece of documentation I quoted also exist(ed) for the AMD allocator. Version 2 made a lot of changes. I want to update this crate to reflect those changes at some point. BTW I have released a new patch version of this crate.

**Comment by zimond** [comment]
Oh, maybe I misunderstood the documentation?

Every allocation returned (could) be just different ranges of the same underlying device memory. Indeed mapping the same memory multiple times leads to error. That's why an extra lock is needed when mapping the allocated memory range. But as long as the range do not conflict between threads, everything is ok.

 I think the allocator is not responsible for mapping/unmapping the memory. So I said it could be used across threads.
